[package]
name = "kv_cli"
version = "0.1.0"

[[target.bin]]
name = "kv_cli"
path = "src/main.fzy"

[profiles.dev]
optimize = true
checks = true

[profiles.release]
optimize = true
checks = true

[profiles.verify]
optimize = false
checks = true
