[package]
name = "hir"
version.workspace = true
edition.workspace = true

[dependencies]
ast = { path = "../ast" }
capabilities = { path = "../capabilities" }

[dev-dependencies]
parser = { path = "../parser" }
