[package]
name = "fullstack"
version = "0.1.0"

[[target.bin]]
name = "fullstack"
path = "src/main.fzy"

[ffi]
panic_boundary = "error"

[unsafe]
contracts = "compiler"
enforce_dev = false
enforce_verify = true
enforce_release = true
