[package]
name = "verifier"
version.workspace = true
edition.workspace = true

[dependencies]
fir = { path = "../fir" }
diagnostics = { path = "../diagnostics" }
capabilities = { path = "../capabilities" }
ast = { path = "../ast" }
