[package]
name = "fz"
version.workspace = true
edition.workspace = true
default-run = "fz"

[[bin]]
name = "fz"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
driver = { path = "../../crates/driver" }
serde_json.workspace = true
