[package]
name = "robust_cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
core = { path = "../../crates/core" }
stdlib = { path = "../../crates/stdlib" }
