[package]
name = "robust_cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
capabilities = { path = "../../crates/capabilities" }
stdlib = { path = "../../crates/stdlib" }
